# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/users
Accept: application/json

###

GET http://127.0.0.1:8000/user/c127e886-64ca-4188-a7ce-7625faa4e80d
Accept: application/json

###

GET http://127.0.0.1:8000/delete/1
Accept: application/json

###

POST http://127.0.0.1:8000/register
Content-Type: application/json

{
    "name": "JohnNick",
    "password": "senha123",
    "email": "johnnick5@hotmail.com",
    "telephone": "32999999999"
}

###

POST http://127.0.0.1:8000/lottery/4
Content-Type: application/json

{
    "name": "Lottery 1",
    "description": "Lottery 1 description",
    "price": 0.0,
    "max_number": 100
}

###

GET http://127.0.0.1:8000/lottery/2
Accept: application/json

###
